"""add is_admin to users

Revision ID: 4cc7ab3a2a22
Revises: a646bfcd7dd6
Create Date: 2026-02-18 06:00:38.657466
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cc7ab3a2a22"
down_revision: str | None = "a646bfcd7dd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.create_index(op.f("ix_users_is_admin"), "users", ["is_admin"], unique=False)
    op.alter_column("users", "is_admin", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_admin"), table_name="users")
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
