"""initial_schema

Revision ID: a646bfcd7dd6
Revises: 
Create Date: 2026-02-16 16:15:27.946072
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a646bfcd7dd6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_usage_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('prompt_template', sa.String(length=100), nullable=True),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_log_created_at'), 'ai_usage_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_log_provider'), 'ai_usage_log', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_usage_log_task_type'), 'ai_usage_log', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_usage_log_ticker'), 'ai_usage_log', ['ticker'], unique=False)
    op.create_index(op.f('ix_ai_usage_log_user_id'), 'ai_usage_log', ['user_id'], unique=False)
    op.create_table('assumption_sets',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revenue_growth_rates', sa.Text(), nullable=False),
    sa.Column('projection_years', sa.Integer(), nullable=False),
    sa.Column('gross_margin', sa.Float(), nullable=False),
    sa.Column('operating_margin', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('wacc', sa.Float(), nullable=False),
    sa.Column('terminal_growth_rate', sa.Float(), nullable=False),
    sa.Column('capex_as_pct_revenue', sa.Float(), nullable=False),
    sa.Column('da_as_pct_revenue', sa.Float(), nullable=False),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('net_debt', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumption_sets_is_active'), 'assumption_sets', ['is_active'], unique=False)
    op.create_index(op.f('ix_assumption_sets_stock_id'), 'assumption_sets', ['stock_id'], unique=False)
    op.create_index(op.f('ix_assumption_sets_user_id'), 'assumption_sets', ['user_id'], unique=False)
    op.create_table('news_analyses',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('impact_label', sa.String(length=20), nullable=False),
    sa.Column('thesis_alignment', sa.String(length=20), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('affected_metrics', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('provider_sentiment_score', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_analyses_stock_id'), 'news_analyses', ['stock_id'], unique=False)
    op.create_index(op.f('ix_news_analyses_user_id'), 'news_analyses', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('extracted_sentiment', sa.String(length=20), nullable=True),
    sa.Column('extracted_key_points', sa.Text(), nullable=True),
    sa.Column('extracted_price_target', sa.Float(), nullable=True),
    sa.Column('extracted_metrics', sa.Text(), nullable=True),
    sa.Column('is_ai_processed', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_stock_id'), 'notes', ['stock_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('price_history',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'bar_date', name='uq_price_history_stock_date')
    )
    op.create_index(op.f('ix_price_history_bar_date'), 'price_history', ['bar_date'], unique=False)
    op.create_index(op.f('ix_price_history_stock_id'), 'price_history', ['stock_id'], unique=False)
    op.create_table('theses',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('stance', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('current_price_at_generation', sa.Float(), nullable=True),
    sa.Column('upside_pct', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theses_stock_id'), 'theses', ['stock_id'], unique=False)
    op.create_index(op.f('ix_theses_user_id'), 'theses', ['user_id'], unique=False)
    op.create_table('watch_items',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('potential_impact', sa.Text(), nullable=True),
    sa.Column('impact_direction', sa.String(length=20), nullable=True),
    sa.Column('affected_assumptions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_outcome', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_items_status'), 'watch_items', ['status'], unique=False)
    op.create_index(op.f('ix_watch_items_stock_id'), 'watch_items', ['stock_id'], unique=False)
    op.create_index(op.f('ix_watch_items_user_id'), 'watch_items', ['user_id'], unique=False)
    op.create_table('portfolio_stocks',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', 'stock_id')
    )
    op.create_table('scenarios',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assumption_set_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('revenue_growth_rate', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('wacc', sa.Float(), nullable=True),
    sa.Column('terminal_growth_rate', sa.Float(), nullable=True),
    sa.Column('dcf_per_share', sa.Float(), nullable=True),
    sa.Column('comps_implied_pe', sa.Float(), nullable=True),
    sa.Column('comps_implied_ev_ebitda', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assumption_set_id'], ['assumption_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_assumption_set_id'), 'scenarios', ['assumption_set_id'], unique=False)
    op.create_index(op.f('ix_scenarios_stock_id'), 'scenarios', ['stock_id'], unique=False)
    op.create_index(op.f('ix_scenarios_user_id'), 'scenarios', ['user_id'], unique=False)
    op.create_table('thesis_changes',
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('previous_stance', sa.String(length=20), nullable=True),
    sa.Column('new_stance', sa.String(length=20), nullable=True),
    sa.Column('previous_target_price', sa.Float(), nullable=True),
    sa.Column('new_target_price', sa.Float(), nullable=True),
    sa.Column('previous_confidence', sa.Float(), nullable=True),
    sa.Column('new_confidence', sa.Float(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('version_from', sa.Integer(), nullable=False),
    sa.Column('version_to', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_changes_created_at'), 'thesis_changes', ['created_at'], unique=False)
    op.create_index(op.f('ix_thesis_changes_thesis_id'), 'thesis_changes', ['thesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_changes_thesis_id'), table_name='thesis_changes')
    op.drop_index(op.f('ix_thesis_changes_created_at'), table_name='thesis_changes')
    op.drop_table('thesis_changes')
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_stock_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_assumption_set_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('portfolio_stocks')
    op.drop_index(op.f('ix_watch_items_user_id'), table_name='watch_items')
    op.drop_index(op.f('ix_watch_items_stock_id'), table_name='watch_items')
    op.drop_index(op.f('ix_watch_items_status'), table_name='watch_items')
    op.drop_table('watch_items')
    op.drop_index(op.f('ix_theses_user_id'), table_name='theses')
    op.drop_index(op.f('ix_theses_stock_id'), table_name='theses')
    op.drop_table('theses')
    op.drop_index(op.f('ix_price_history_stock_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_bar_date'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_stock_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_news_analyses_user_id'), table_name='news_analyses')
    op.drop_index(op.f('ix_news_analyses_stock_id'), table_name='news_analyses')
    op.drop_table('news_analyses')
    op.drop_index(op.f('ix_assumption_sets_user_id'), table_name='assumption_sets')
    op.drop_index(op.f('ix_assumption_sets_stock_id'), table_name='assumption_sets')
    op.drop_index(op.f('ix_assumption_sets_is_active'), table_name='assumption_sets')
    op.drop_table('assumption_sets')
    op.drop_index(op.f('ix_ai_usage_log_user_id'), table_name='ai_usage_log')
    op.drop_index(op.f('ix_ai_usage_log_ticker'), table_name='ai_usage_log')
    op.drop_index(op.f('ix_ai_usage_log_task_type'), table_name='ai_usage_log')
    op.drop_index(op.f('ix_ai_usage_log_provider'), table_name='ai_usage_log')
    op.drop_index(op.f('ix_ai_usage_log_created_at'), table_name='ai_usage_log')
    op.drop_table('ai_usage_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
